kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.drill.id }}-rb
subjects:
  - kind: ServiceAccount
    name: {{ .Values.drill.id }}-sa
    namespace: {{.Release.namespace}}
roleRef:
  kind: Role
  name: {{ .Values.drill.id }}-role
  apiGroup: rbac.authorization.k8s.io

